insert into categoryVideo(category_id,category) values ('1','Film & Animation');
insert into categoryVideo(category_id,category) values ('2','Autos & Vehicles');
insert into categoryVideo(category_id,category) values ('10','Music');
insert into categoryVideo(category_id,category) values ('15','Pets & Animals');
insert into categoryVideo(category_id,category) values ('17','Sports');
insert into categoryVideo(category_id,category) values ('18','Short Movies');
insert into categoryVideo(category_id,category) values ('19','Travel & Events');
insert into categoryVideo(category_id,category) values ('20','Gaming');
insert into categoryVideo(category_id,category) values ('21','Videoblogging');
insert into categoryVideo(category_id,category) values ('22','People & Blogs');
insert into categoryVideo(category_id,category) values ('23','Comedy');
insert into categoryVideo(category_id,category) values ('24','Entertainment');
insert into categoryVideo(category_id,category) values ('25','News & Politics');
insert into categoryVideo(category_id,category) values ('26','Howto & Style');
insert into categoryVideo(category_id,category) values ('27','Education');
insert into categoryVideo(category_id,category) values ('28','Science & Technology');
insert into categoryVideo(category_id,category) values ('30','Movies');
insert into categoryVideo(category_id,category) values ('31','Anime/Animation');
insert into categoryVideo(category_id,category) values ('32','Action/Adventure');
insert into categoryVideo(category_id,category) values ('33','Classics');
insert into categoryVideo(category_id,category) values ('34','Comedy');
insert into categoryVideo(category_id,category) values ('35','Documentary');
insert into categoryVideo(category_id,category) values ('36','Drama');
insert into categoryVideo(category_id,category) values ('37','Family');
insert into categoryVideo(category_id,category) values ('38','Foreign');
insert into categoryVideo(category_id,category) values ('39','Horror');
insert into categoryVideo(category_id,category) values ('40','Sci-Fi/Fantasy');
insert into categoryVideo(category_id,category) values ('41','Thriller');
insert into categoryVideo(category_id,category) values ('42','Shorts');
insert into categoryVideo(category_id,category) values ('43','Shows');
insert into categoryVideo(category_id,category) values ('44','Trailers');
